name: DynamicSD
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.14
  - binutils_impl_linux-64=2.44
  - bioconductor-biobase=2.66.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocio=1.16.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-biostrings=2.74.0
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.32.0
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-genomicalignments=1.42.0
  - bioconductor-genomicranges=1.58.0
  - bioconductor-iranges=2.40.0
  - bioconductor-matrixgenerics=1.18.0
  - bioconductor-noiseq=2.50.0
  - bioconductor-rhtslib=3.2.0
  - bioconductor-rsamtools=2.22.0
  - bioconductor-rtracklayer=1.66.0
  - bioconductor-s4arrays=1.6.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-sparsearray=1.6.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - curl=8.14.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=15.1.0
  - gfortran_impl_linux-64=15.1.0
  - giflib=5.2.2
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.1.0
  - harfbuzz=11.4.4
  - icu=75.1
  - jq=1.8.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.3
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsanitizer=15.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - make=4.4.1
  - ncurses=6.5
  - oniguruma=6.9.10
  - openjdk=23.0.2
  - openssl=3.5.2
  - pango=1.56.4
  - pcre2=10.45
  - pixman=0.46.4
  - pthread-stubs=0.4
  - python=3.9.23
  - python_abi=3.9
  - qualimap=2.3
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-base=4.4.3
  - r-bh=1.87.0_1
  - r-bitops=1.0_9
  - r-codetools=0.2_20
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-curl=7.0.0
  - r-formatr=1.14
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.4
  - r-httr=1.4.7
  - r-jsonlite=2.0.0
  - r-lambda.r=1.2.4
  - r-lattice=0.22_7
  - r-matrix=1.7_3
  - r-matrixstats=1.5.0
  - r-mime=0.13
  - r-openssl=2.3.3
  - r-optparse=1.7.5
  - r-r6=2.6.1
  - r-rcurl=1.98_1.17
  - r-restfulr=0.0.16
  - r-rjson=0.2.23
  - r-snow=0.4_4
  - r-sys=3.4.3
  - r-xml=3.99_0.17
  - r-yaml=2.3.10
  - readline=8.2
  - sed=4.9
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomlkit=0.13.3
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - yaml=0.2.5
  - zstd=1.5.7
  - pip:
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - anndata==0.9.2
      - appdirs==1.4.4
      - argcomplete==1.12.3
      - array-api-compat==1.4
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==23.2.0
      - botocore==1.31.17
      - bottleneck==1.3.5
      - brotli==1.0.9
      - cached-property==1.5.2
      - cellpose==2.2.3
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==2.0.4
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - conda-pack==0.7.1
      - configargparse==1.7
      - contourpy==1.1.1
      - cramjam==2.10.0
      - cryptography==41.0.7
      - cycler==0.11.0
      - dask==2024.8.0
      - dask-expr==1.1.10
      - dask-image==2024.5.3
      - datashader==0.17.0
      - datrie==0.8.2
      - decorator==5.1.1
      - dill==0.3.7
      - distributed==2024.8.0
      - docutils==0.20.1
      - exceptiongroup==1.0.4
      - executing==2.1.0
      - fasteners==0.19
      - fastparquet==2024.11.0
      - fastremap==1.17.3
      - filelock==3.13.1
      - fonttools==4.25.0
      - frozenlist==1.7.0
      - fsspec==2023.6.0
      - future==1.0.0
      - geopandas==1.0.1
      - get-annotations==0.1.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - gmpy2==2.1.2
      - h5py==3.10.0
      - idna==3.4
      - igraph==0.11.3
      - imagecodecs==2024.12.30
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.1.1
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.4
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - llvmlite==0.41.1
      - locket==1.0.0
      - mappy==2.28
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - munkres==1.1.4
      - natsort==7.1.1
      - networkx==3.1
      - numba==0.58.1
      - numcodecs==0.12.1
      - numexpr==2.8.7
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - ome-zarr==0.10.2
      - opencv-python-headless==4.8.0.74
      - packaging==23.1
      - pandarallel==1.6.4
      - pandas==2.1.4
      - param==2.2.1
      - parso==0.8.4
      - partd==1.4.2
      - patsy==0.5.3
      - pexpect==4.9.0
      - pillow==10.0.1
      - pims==0.7
      - pip==23.3.1
      - platformdirs==4.3.8
      - plotly==5.18.0
      - ply==3.11
      - pooch==1.8.2
      - prompt-toolkit==3.0.48
      - propcache==0.3.2
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pybktree==1.1
      - pycparser==2.21
      - pyct==0.5.0
      - pygments==2.18.0
      - pynndescent==0.5.10
      - pyogrio==0.11.0
      - pyopenssl==23.2.0
      - pyparsing==3.0.9
      - pyproj==3.6.1
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.13.0
      - pysam==0.22.0
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - ratelimiter==1.2.0.post0
      - referencing==0.32.1
      - regex==2024.5.15
      - requests==2.31.0
      - rich==14.0.0
      - roifile==2024.9.15
      - rpds-py==0.16.2
      - s3fs==2023.6.0
      - scanpy==1.9.6
      - scikit-image==0.24.0
      - scikit-learn==1.3.0
      - scipy==1.11.4
      - seaborn==0.12.2
      - session-info==1.0.0
      - setuptools==68.2.2
      - shapely==2.0.7
      - sip==6.7.12
      - six==1.16.0
      - slicerator==1.1.0
      - smmap==5.0.1
      - snakemake==5.4.5
      - sortedcontainers==2.4.0
      - spatial-image==1.1.0
      - spatialdata==0.2.5
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - stdlib-list==0.8.0
      - sympy==1.12
      - tblib==3.1.0
      - tenacity==8.2.3
      - texttable==1.7.0
      - threadpoolctl==2.2.0
      - tifffile==2024.8.30
      - tomli==2.0.1
      - toolz==1.0.0
      - torch==2.1.2
      - tornado==6.5.2
      - tqdm==4.65.0
      - traitlets==5.14.3
      - triton==2.1.0
      - typing-extensions==4.14.1
      - tzdata==2023.3
      - umap-learn==0.5.3
      - umi-tools==1.1.4
      - urllib3==1.26.18
      - wcwidth==0.2.13
      - wheel==0.41.2
      - wrapt==1.16.0
      - xarray==2024.7.0
      - xarray-dataclasses==1.9.1
      - xarray-datatree==0.0.15
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xmltodict==0.13.0
      - yarl==1.20.1
      - yq==2.12.0
      - zarr==2.18.2
      - zict==3.0.0
      - zipp==3.23.0
      - antspyx==0.6.1
